export enum DocumentStatus {
  PENDING = 'PENDING',
  ONCHAIN_CONFIRMED = 'ONCHAIN_CONFIRMED',
  NOTARY_SIGNED = 'NOTARY_SIGNED',
  FULLY_EXECUTED = 'FULLY_EXECUTED',
  DISPUTED = 'DISPUTED',
  REVOKED = 'REVOKED'
}

export enum UserRole {
  CITIZEN = 'CITIZEN',
  NOTARY = 'NOTARY',
  BANK_OFFICER = 'BANK_OFFICER',
  COURT_CLERK = 'COURT_CLERK',
  ADMIN = 'ADMIN'
}

export enum SignerRole {
  NOTARY = 'NOTARY',
  BUYER = 'BUYER',
  SELLER = 'SELLER',
  OTHER = 'OTHER'
}
